import type {EditableTemplate,EditableData} from './editable-contract'
import {renderEditableHtml} from './editable-render'
import {EDITABLE_RENDER_RUNTIME} from './editable-render-runtime'

export function editableHtmlDocument(template: EditableTemplate, data: EditableData):string {
  const json=(v:unknown)=>JSON.stringify(v).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')
  // User text stays in JSON or escaped text nodes. No source/model code executes.
  return `<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Редактируемая конструкция</title><style>body{margin:0;padding:24px;background:#f5f7fa;font-family:Arial,sans-serif}main{max-width:1200px;margin:auto;background:white}details{max-width:1200px;margin:20px auto}textarea{box-sizing:border-box;width:100%;min-height:280px;font:14px/1.5 monospace;padding:15px}button{padding:12px;margin-top:8px}#error{color:#a22}</style><main id="preview">${renderEditableHtml(template,data)}</main><details><summary>Изменить данные</summary><p>Текст, числа, строки и ряды меняются независимо от оформления.</p><textarea id="data" aria-label="Данные"></textarea><button id="apply">Применить</button><p id="error" role="alert"></p></details><script>const template=${json(template)};let data=${json(data)};${EDITABLE_RENDER_RUNTIME}; const renderEditableHtml=MspEditableRender.renderEditableHtml;document.getElementById('data').value=JSON.stringify(data,null,2);MspEditableRender.hydrateEditableHtml(document.getElementById('preview'));document.getElementById('apply').onclick=async()=>{try{const next=JSON.parse(document.getElementById('data').value);if(!next||typeof next!=='object'||Array.isArray(next))throw Error('Нужен объект данных');document.getElementById('preview').innerHTML=renderEditableHtml(template,next);await MspEditableRender.hydrateEditableHtml(document.getElementById('preview'));data=next;document.getElementById('error').textContent=''}catch(e){document.getElementById('error').textContent='Проверьте данные: '+e.message}};</script></html>`
}
