import { z } from 'zod'
const text=z.string().max(100000),num=z.number().finite(),point=z.number().finite().nullable(),color=z.string().regex(/^#[\da-f]{6}$/i)
export const nativeChartSchema=z.object({kind:z.literal('chart'),sourcePart:z.string().max(400),groups:z.array(z.object({type:z.string().max(60),grouping:z.string().max(60),horizontal:z.boolean(),hole:num.min(0).max(1),series:z.array(z.object({name:text,categories:z.array(text).max(2000),values:z.array(point).max(2000),format:z.string().max(300),x:z.array(point).max(2000),sizes:z.array(point).max(2000),axis:z.enum(['left','right']),color:color.optional(),colors:z.array(color.nullable()).max(2000),smooth:z.boolean()}).strict()).max(32)}).strict()).max(16),title:text.optional(),style:z.object({font:z.string().max(120),palette:z.array(color).max(16),background:color.optional(),color:color.optional(),grid:z.boolean(),axis:z.boolean(),labels:z.boolean()}).strict().optional(),legend:z.boolean(),warnings:z.array(z.string().max(300)).max(1000)}).strict()
export const nativeDiagramSchema=z.object({kind:z.literal('smartart'),sourcePart:z.string().max(400),nodes:z.array(z.object({id:z.string().min(1).max(128),text}).strict()).max(2048),edges:z.array(z.object({from:z.string().max(128),to:z.string().max(128),order:num.int().min(0)}).strict()).max(4096),algorithms:z.array(z.string().max(60)).max(1000),layoutName:z.string().max(500),dataXml:z.string().max(2000000),layoutXml:z.string().max(2000000)}).strict().superRefine((d,ctx)=>{
  const ids=new Set(d.nodes.map(n=>n.id));if(ids.size!==d.nodes.length||d.edges.some(e=>!ids.has(e.from)||!ids.has(e.to)||e.from===e.to))ctx.addIssue({code:z.ZodIssueCode.custom,message:'Invalid diagram references'})
  const parents=new Map(d.edges.map(e=>[e.to,e.from]));for(const id of ids){const seen=new Set<string>();let at:string|undefined=id;while(at){if(seen.has(at)){ctx.addIssue({code:z.ZodIssueCode.custom,message:'Cyclic diagram'});break}seen.add(at);at=parents.get(at)}}
})
export const nativeTableSchema=z.object({kind:z.literal('table'),sourcePart:z.string().max(400),columns:z.array(num.positive()).min(1).max(60),rows:z.array(z.object({height:num.positive(),cells:z.array(z.object({text,colSpan:num.int().positive().max(60),rowSpan:num.int().positive().max(2000),merged:z.boolean()}).strict()).max(60)}).strict()).max(2000)}).strict()
export const nativeObjectSchema=z.union([nativeChartSchema,nativeDiagramSchema,nativeTableSchema])
export type NativeChart=z.infer<typeof nativeChartSchema>
export type NativeDiagram=z.infer<typeof nativeDiagramSchema>
export type NativeTable=z.infer<typeof nativeTableSchema>
