import { build } from 'esbuild';
import { readFile,writeFile,readdir } from 'node:fs/promises';
import { dirname,resolve } from 'node:path';
await build({entryPoints:['browser/prepare.ts'],outfile:'public/pptx-reader.js',bundle:true,format:'iife',globalName:'MspPptxReader',platform:'browser',target:'es2022',minify:true});

// Minified third-party license comments can contain trailing whitespace.
const built=await readFile('public/pptx-reader.js','utf8');
await writeFile('public/pptx-reader.js',built.replace(/[ \t]+$/gm,''));

// Extraction and rendering must use identical, unoptimized PDF operator IDs.
const worker='node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs';
const source=await readFile(worker,'utf8');
const needle='this.optimizer = streamSink && !(intent & RenderingIntentFlag.OPLIST) ? new QueueOptimizer(this) : new NullOptimizer(this);';
if(source.split(needle).length!==2)throw new Error('PDF optimizer contract changed');
await writeFile(worker.replace('pdf.worker','pdf.editable.worker'),source.replace(needle,'this.optimizer = new NullOptimizer(this);'));
const resources={},notices=[];
for(const [folder,kind,extensions] of [['standard_fonts','standardFontDataUrl',['.pfb','.ttf']],['cmaps','cMapUrl',['.bcmap']],['wasm','',[]]]){
  const base=resolve('node_modules/pdfjs-dist',folder);
  for(const name of (await readdir(base)).sort()){
    if(extensions.some(ext=>name.endsWith(ext)))resources[`${kind}/${name}`]=(await readFile(resolve(base,name))).toString('base64');
    if(/LICENSE/i.test(name))notices.push(`${folder}/${name}\n${await readFile(resolve(base,name),'utf8')}`);
  }
}
await build({entryPoints:['browser/pdf-source.ts'],outfile:'public/pdf-reader.js',bundle:true,format:'iife',globalName:'MspPdfReader',platform:'browser',target:'es2022',minify:true,
  define:{__PDF_LOCAL_RESOURCES__:JSON.stringify(resources)},
  plugins:[{name:'local-pdf-decoders',setup(build){build.onLoad({filter:/pdfjs-dist\/legacy\/build\/pdf\.editable\.worker\.mjs$/},async({path})=>{
    const source=await readFile(path,'utf8');
    const decoder=/await import\(\s*\/\*webpackIgnore: true\*\/\s*\/\*@vite-ignore\*\/\s*`\$\{WasmImage\.#wasmUrl\}\$\{this\._noWasmFilename\}`\)/g;
    if([...source.matchAll(decoder)].length!==1)throw new Error('PDF decoder contract changed');
    return {contents:source.replace(decoder,'await (this._noWasmFilename === "openjpeg_nowasm_fallback.js" ? import("../../wasm/openjpeg_nowasm_fallback.js") : this._noWasmFilename === "jbig2_nowasm_fallback.js" ? import("../../wasm/jbig2_nowasm_fallback.js") : Promise.reject(new Error("pdf-resource-unavailable")))'),loader:'js',resolveDir:dirname(path)};
  })}}]});
await writeFile('public/pdf-reader.js',(await readFile('public/pdf-reader.js','utf8')).replace(/[ \t]+$/gm,''));
await writeFile('public/pdf-resource-licenses.txt',notices.join('\n\n'));

// Offline HTML uses a built standalone module, never a transpiler's function.toString().
const runtime=await build({entryPoints:['lib/design-system/editable-runtime.ts'],bundle:true,format:'iife',globalName:'MspEditableRender',platform:'browser',target:'es2022',minify:true,write:false});
await writeFile('lib/design-system/editable-render-runtime.ts','// Generated by reader:build; edit editable-render.ts.\nexport const EDITABLE_RENDER_RUNTIME='+JSON.stringify(runtime.outputFiles[0].text)+'\n');
