import { shapes, sampleNames } from '../lib/component-lab/cases'
export const names = { vertical: 'Вертикально', horizontal: 'Горизонтально', compact: 'Компактно' }
export const esc = (v: unknown) => String(v).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!))
const segments = (id: string, label: string, values: Record<string, string>) => `<div class="control"><span id="${id}-label">${label}</span><div id="${id}" class="segments" role="group" aria-labelledby="${id}-label">${Object.entries(values).map(([value, name]) => `<button type="button" data-value="${value}" aria-pressed="false">${name}</button>`).join('')}</div></div>`
export const editorView = (workspace = false) => `<header><div><a id="bank-link" href="${workspace ? '/styles' : 'http://127.0.0.1:5184/styles'}" ${workspace ? '' : 'target="_blank" rel="noreferrer"'}>${workspace ? '← К компонентам' : 'MSP / Банк стилей'}</a><h1>Настроить компонент</h1></div><div class="source-pickers"><label ${workspace ? 'hidden' : ''}>Дизайн-система<select id="style"></select></label><label>Компонент<select id="component"></select></label></div></header>
<div id="notice" role="status" aria-live="polite">Загружаем библиотеку…</div>
<div id="background-preparation" hidden><span id="background-preparation-text" class="muted" role="status" aria-live="polite"></span> <button id="background-preparation-retry" type="button" class="text-button" hidden>Повторить проверку</button></div>
<div class="editor-layout"><aside id="unprepared-panel" hidden><h2>Адаптация ещё не готова</h2><p id="unprepared-reason" class="muted"></p><p class="muted">Исходный вид сохранён. Настройки появятся, когда система сможет менять расположение полей без потери оформления и текста.</p><a id="original-slide" target="_blank" rel="noreferrer">Открыть исходный слайд ↗</a></aside><aside data-adaptive-controls><h2>Поведение</h2><label>Вид компонента<select id="state"><option value="auto">Подобрать по форме</option></select></label><p id="scope" class="muted">Настройки выбранного компонента</p>
${segments('alignment', 'Выравнивание текста', { source: 'Исходное', left: 'Слева', center: 'По центру', right: 'Справа' })}
${segments('position', 'Положение в карточке', { top: 'Сверху', center: 'По центру', bottom: 'Снизу' })}
<label>Расстояние между полями<select id="gap"><option value="">Исходное</option><option value="12">Компактно</option><option value="20">Обычно</option><option value="32">Свободно</option></select></label>
<details id="advanced"><summary>Ещё настройки</summary><div class="detail-content"><label>Внутренний отступ<input id="padding" type="number" min="12" max="48" step="1" placeholder="Исходный"></label><label>Ширина содержимого, %<input id="content-width" type="number" min="50" max="100" value="100"></label><button id="source-rules" class="text-button">Вернуть исходные правила</button></div></details>
<div class="save-area"><button id="save" class="primary" disabled>Сохранить правила</button><button id="cancel" hidden>Остановить проверку</button><p id="save-status" role="status" aria-live="polite">Правила ещё не сохранены</p><button id="reset" class="text-button" disabled>Отменить мои изменения</button></div>
<details id="history"><summary>История версий</summary><div class="detail-content"><label>Сохранённая версия<select id="versions"></select></label><button id="restore" disabled>Вернуть эту версию</button><p class="muted">Возврат станет новой версией после сохранения.</p></div></details>
<p class="integration-note">Правила сохраняются в дизайн-системе. Для генерации требуется отдельный допуск; готовые слайды не меняются.</p></aside>
<section class="workspace"><div class="stage-head"><div><h2 id="component-title">Выберите компонент</h2><p id="dimensions" class="muted"></p></div><span id="status" class="pill">Ожидание</span></div>
<div class="preview-toolbar" data-adaptive-controls><div id="shapes" class="chips" aria-label="Форма для просмотра">${shapes.map(s => `<button type="button" data-shape="${s.id}" aria-pressed="false">${s.name}</button>`).join('')}</div><details id="box-settings"><summary>Свои размеры</summary><div class="box-inputs"><label>Ширина<input id="width" type="number" min="120" max="1200" step="10" value="600"></label><label>Высота<input id="height" type="number" min="60" max="1000" step="10" value="400"></label><label>Высота компонента<select id="height-mode"><option value="fill">Заполнять область</option><option value="hug">По содержанию</option></select></label></div></details></div>
<div class="stage"><div id="viewport"><div id="preview"></div></div></div><div id="result" role="status" aria-live="polite"></div><p id="font-note" class="muted" hidden></p>
<div class="content-toolbar" data-adaptive-controls><label>Текст для просмотра<select id="sample"><option value="source">Из исходника</option>${Object.entries(sampleNames).map(([id, name]) => `<option value="${id}">${name}</option>`).join('')}<option value="custom">Свой текст</option></select></label><details id="content-fields"><summary>Изменить текст примера</summary><div id="fields" class="detail-content"></div></details></div>
<details id="verification" class="quality" data-adaptive-controls><summary>Проверка разных условий <span id="progress">Ещё не проверено</span></summary><div class="detail-content"><p id="quality-note"></p><div class="actions"><button id="run" disabled>Проверить все сочетания</button><button id="download" disabled>Скачать отчёт</button></div><div id="cases" class="cases"></div></div></details>
<details class="source" data-adaptive-controls><summary>Исходный образец</summary><div id="source-preview"></div></details><details class="source" ${workspace ? 'hidden' : ''}><summary>Другие конструкции</summary><ul id="unsupported"></ul></details></section></div>`
