import { test, expect, openTestProject } from './workspace-fixture'
import type { Page } from '@playwright/test'
import { controlPptx } from '../fixtures/control-pptx'

async function importStyle(page: Page, name: string) {
  await page.goto('/styles'); await page.waitForLoadState('networkidle')
  await page.getByLabel('PPTX или PDF дизайн-системы').setInputFiles({ name: `${name}.pptx`, mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', buffer: await controlPptx() })
  await expect(page.locator('.cw-list button').first()).toBeVisible({ timeout: 60000 })
  return new URL(page.url()).pathname.split('/').at(-1)!
}

test('project cards lead to content and style; import, generation action, autosave and style changes persist', async ({ page, request }, info) => {
  expect((await (await request.get('/api/capabilities/qwen')).json()).configured).toBe(false)
  const firstStyle = await importStyle(page, 'Оформление проекта')
  const secondStyle = await importStyle(page, 'Второе оформление')
  await page.getByRole('link', { name: 'Создать презентацию', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/projects\\?template=${secondStyle}$`))
  await expect(page.getByRole('heading', { name: 'Новый проект', exact: true })).toBeVisible()
  const contentField = page.locator('#presentation-content'), styleField = page.getByRole('radiogroup', { name: 'Дизайн-система', exact: true })
  await expect(styleField.locator(`input[value="${secondStyle}"]`)).toBeChecked()
  await expect(page.locator('.cw-list,.ws-project-tabs,.slide-composer,.ws-project-card')).toHaveCount(0)
  await expect(page.getByLabel('Название проекта', { exact: true })).toHaveCount(0)
  await expect(page.locator('input[accept=".pptx"]')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Сгенерировать слайды', exact: true })).toBeDisabled()
  await page.screenshot({ path: info.outputPath('projects-desktop.png'), fullPage: true })
  for (const width of [1024, 720, 390, 320]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(styleField).toBeVisible()
    if (width === 390) await page.screenshot({ path: info.outputPath('projects-mobile.png'), fullPage: true })
  }
  await page.setViewportSize({ width: 1440, height: 1100 })
  const content = '# Программа развития\n\nПолный текст: 100 участников, бюджет & сроки.\n\n# Результат\nБез потери исходного содержания.'
  await page.getByLabel('Файл содержания').setInputFiles({ name: 'Программа.md', mimeType: 'text/markdown', buffer: Buffer.from(content) })
  await expect(contentField).toHaveValue(content)
  await page.getByLabel('Файл содержания').setInputFiles({ name: 'Ошибка.pdf', mimeType: 'application/pdf', buffer: Buffer.from('wrong type') })
  await expect(page.getByRole('alert')).toContainText('Выберите TXT, MD, CSV, TSV, JSON или XLSX')
  await expect(contentField).toHaveValue(content)
  await styleField.locator(`input[value="${firstStyle}"]`).check()
  await page.getByRole('button', { name: 'Сгенерировать слайды', exact: true }).click()
  await page.waitForURL(/\/projects\/[a-f0-9-]{36}$/)
  const projectId = new URL(page.url()).pathname.split('/').at(-1)!
  await page.getByRole('button', { name: 'Содержание и параметры' }).click()
  await expect(contentField).toHaveValue(content)
  await expect(styleField.locator(`input[value="${firstStyle}"]`)).toBeChecked()
  await expect(page.getByRole('status').filter({ hasText: 'Все изменения сохранены' })).toBeVisible()
  await expect(page.locator('.cw-list,.ws-project-tabs')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Сохранить содержание|Добавить выбранный компонент|Скачать PPTX/ })).toHaveCount(0)
  const updated = content + '\n\nДополнение: сохранить все факты.'
  await contentField.fill(updated)
  await styleField.locator(`input[value="${secondStyle}"]`).check()
  await expect(page.getByRole('status').filter({ hasText: 'Все изменения сохранены' })).toBeVisible()
  const saved = (await (await request.get(`/api/projects/${projectId}`)).json()).project
  expect(saved).toMatchObject({ name: 'Программа', text: updated, uploadId: secondStyle, styleName: 'Второе оформление' })
  await page.reload()
  await page.getByRole('button', { name: 'Содержание и параметры' }).click()
  await expect(contentField).toHaveValue(updated)
  await expect(styleField.locator(`input[value="${secondStyle}"]`)).toBeChecked()
  await page.screenshot({ path: info.outputPath('project-saved.png'), fullPage: true })
  const secondId = await openTestProject(page, request, firstStyle)
  expect((await (await request.get(`/api/projects/${secondId}`)).json()).project.text).not.toBe(updated)
  await page.goto(`/projects/${projectId}`)
  await expect(contentField).toHaveValue(updated)
  await page.getByRole('navigation', { name: 'Основная навигация' }).getByRole('link', { name: 'Проекты', exact: true }).click()
  await expect(page).toHaveURL(/\/projects$/)
  await expect(contentField).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Открыть проект Программа', exact: true })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Найти проект' }).fill('Программа')
  await expect(page.locator('.ws-project-tile')).toHaveCount(1)
  await page.getByRole('link', { name: 'Новый проект', exact: true }).click()
  await expect(contentField).toBeEmpty()
  await page.goto('/'); await expect(page.getByRole('heading', { name: 'Дизайн-системы', exact: true })).toBeVisible(); await page.getByRole('link', { name: 'Создать новую презентацию', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Создайте презентацию из вашего текста' })).toBeVisible()
  await expect(contentField).toBeVisible()
  await expect(page.locator('.cw-list')).toHaveCount(0)
  await page.goto('/uploads'); await expect(page).toHaveURL(/\/styles$/)
})

test('autosave retains local content after a failed request and protects concurrent edits', async ({ page, request }) => {
  const uploadId = await importStyle(page, 'Контроль сохранения')
  const id = await openTestProject(page, request, uploadId)
  const field = page.locator('#presentation-content')
  const endpoint = `/api/projects/${id}`
  await page.route(`**${endpoint}`, async route => {
    if (route.request().method() === 'PUT') await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Не удалось сохранить изменения. Попробуйте ещё раз.' }) })
    else await route.continue()
  })
  await field.fill('Текст, который нельзя потерять при ошибке сети.')
  await expect(page.getByRole('alert')).toContainText('Не удалось сохранить изменения')
  await expect(field).toHaveValue('Текст, который нельзя потерять при ошибке сети.')
  await page.unroute(`**${endpoint}`)
  await page.getByRole('button', { name: 'Повторить сохранение' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Все изменения сохранены' })).toBeVisible()
  const saved = (await (await request.get(endpoint)).json()).project
  expect((await request.put(endpoint, { data: { baseRevision: saved.revision, name: saved.name, text: 'Правка из другой вкладки.' } })).ok()).toBe(true)
  await field.fill('Моя новая версия — сохранить отдельно.')
  await expect(page.getByRole('alert')).toContainText('Проект изменён в другой вкладке')
  expect((await (await request.get(endpoint)).json()).project.text).toBe('Правка из другой вкладки.')
  await expect(field).toHaveValue('Моя новая версия — сохранить отдельно.')
  await page.getByRole('button', { name: 'Сохранить отдельным проектом' }).click()
  await page.waitForURL(url => /\/projects\/[a-f0-9-]{36}$/.test(url.pathname) && !url.pathname.endsWith(id))
  await expect(field).toHaveValue('Моя новая версия — сохранить отдельно.')
  await expect(page.getByRole('status').filter({ hasText: 'Все изменения сохранены' })).toBeVisible()
})

test('removing a style requires confirmation, recovers from failure and retains existing projects', async ({ page, request }) => {
  const name = 'Проверка удаления из банка', uploadId = await importStyle(page, name)
  const projectId = await openTestProject(page, request, uploadId)
  const endpoint = `/api/style-bank/${uploadId}`
  const sourceBefore = await (await request.get(`/api/uploads/${uploadId}/design-system`)).json()
  await page.goto('/styles')
  const card = page.getByRole('link', { name: `Открыть дизайн-систему ${name}`, exact: true })
  const trigger = page.getByRole('button', { name: `Удалить дизайн-систему ${name}`, exact: true })
  await trigger.click()
  const dialog = page.getByRole('alertdialog')
  await expect(dialog).toContainText('Уже созданные презентации и их оформление сохранятся.')
  await expect(dialog.getByRole('button', { name: 'Отмена', exact: true })).toBeFocused()
  await dialog.getByRole('button', { name: 'Отмена', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(card).toBeVisible()
  expect((await request.delete(endpoint, { headers: { Origin: 'https://external.invalid' } })).status()).toBe(403)
  expect((await (await request.get('/api/style-bank')).json()).styles.some((s: { id: string }) => s.id === uploadId)).toBe(true)
  await page.route(`**${endpoint}`, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Unavailable' }) }))
  await trigger.click()
  await dialog.getByRole('button', { name: 'Удалить из банка', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('Не удалось удалить дизайн-систему')
  expect((await (await request.get('/api/style-bank')).json()).styles.some((s: { id: string }) => s.id === uploadId)).toBe(true)
  await page.unroute(`**${endpoint}`)
  await dialog.getByRole('button', { name: 'Удалить из банка', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(card).toHaveCount(0)
  await page.reload()
  await expect(card).toHaveCount(0)
  expect((await (await request.get(`/api/uploads/${uploadId}/design-system`)).json()).visual).toEqual(sourceBefore.visual)
  const saved = (await (await request.get(`/api/projects/${projectId}`)).json()).project
  expect(saved.uploadId).toBe(uploadId)
  await page.goto(`/projects/${projectId}`)
  await expect(page.locator(`#presentation-style input[value="${uploadId}"]`)).toBeChecked()
  await page.getByRole('button', { name: 'Содержание и параметры' }).click()
  await page.locator('#presentation-content').fill('После удаления система оформления проекта продолжает работать.')
  await expect(page.getByRole('status').filter({ hasText: 'Все изменения сохранены' })).toBeVisible()
  expect((await (await request.get(`/api/projects/${projectId}`)).json()).project.text).toContain('После удаления')
  expect((await request.post('/api/projects', { data: { id: crypto.randomUUID(), uploadId, name: 'Недоступный стиль', text: 'Новый проект' } })).status()).toBe(409)
})

test('a style can be removed from its detail page on mobile and returns to the bank', async ({ page, request }, info) => {
  const name = 'Удаление со страницы', uploadId = await importStyle(page, name)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: `Удалить дизайн-систему ${name}`, exact: true }).click()
  const dialog = page.getByRole('alertdialog')
  await expect(dialog).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('delete-style-mobile.png') })
  await dialog.getByRole('button', { name: 'Удалить из банка', exact: true }).click()
  await expect(page).toHaveURL(/\/styles$/)
  await expect(page.getByRole('heading', { name: 'Банк стилей', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: `Открыть дизайн-систему ${name}`, exact: true })).toHaveCount(0)
  expect((await (await request.get('/api/style-bank')).json()).styles.some((s: { id: string }) => s.id === uploadId)).toBe(false)
})
